# Generated by Django 4.0.4 on 2022-06-28 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bistro_app', '0003_alter_recipeingredient_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='bistro_app.ingredient'),
            preserve_default=False,
        ),
    ]
