# Generated by Django 4.0.4 on 2022-06-28 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bistro_app', '0004_alter_recipeingredient_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_name',
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='sale_price',
            field=models.FloatField(default=5.5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(to='bistro_app.recipeingredient'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='sale_price',
            field=models.FloatField(default=6.6),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bistro_app.order')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bistro_app.recipeingredient')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bistro_app.menu')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bistro_app.recipeingredient')),
            ],
        ),
    ]
