# Generated by Django 4.0.4 on 2022-07-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bistro_app', '0008_alter_recipe_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_img',
            field=models.ImageField(default='![](media/default.jpg)', upload_to='media'),
        ),
    ]
