# Generated by Django 4.0.4 on 2022-07-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bistro_app', '0010_alter_recipe_recipe_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_img',
            field=models.FileField(default='default.jpg', upload_to='media'),
        ),
    ]
