# Generated by Django 4.0.4 on 2022-07-20 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bistro_app', '0011_alter_recipe_recipe_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=255)),
                ('sale_price', models.FloatField()),
                ('recipes', models.ManyToManyField(to='bistro_app.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bistro_app.category')),
            ],
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bistro_app.salesmenu'),
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
