# Generated by Django 4.0.4 on 2022-07-20 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bistro_app', '0013_salesmenu_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='recipe',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sales_menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bistro_app.salesmenu'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
