# Generated by Django 4.0.4 on 2022-05-23 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bistro_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='created_by',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_name',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
    ]
